#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -f ${CONFIG_DIR}/app/crontab ]]; then
    echo "PATH=/usr/bin:/bin:/usr/local/bin" > /etc/cron.d/crontab
    cat "${CONFIG_DIR}/app/crontab" >> /etc/cron.d/crontab
    chmod 644 /etc/cron.d/crontab
    cat /etc/cron.d/crontab
fi
